# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Docker login sanity check
          command: |
            echo "Docker Pass: $DOCKER_PASS"
            echo "Docker User: $DOCKER_USER"
      - run:
          name: Docker log in
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Docker build
          command: |
            docker build . -t veldrovive/async-search:latest -t veldrovive/async-search:$CIRCLE_BUILD_NUM
      - run:
          name: Docker push
          command: |
            docker push veldrovive/async-search --all-tags
      - run:
          name: Install
          command: |
            ssh -o "StrictHostKeyChecking=no" ubuntu@52.60.230.10 "cd /home/ubuntu/containers/asyncSearch && docker-compose down && docker-compose pull && docker-compose up -d"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  start-build-and-push:
    jobs:
      - build-and-push:
          context:
            - DockerVeldrovive
          filters:
            branches:
              only:
                - main


